# Generated by Django 4.2.4 on 2023-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='direction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='number',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='service_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
