# Generated by Django 4.2.4 on 2023-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorapi', '0002_alter_elevator_current_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
