# Generated by Django 4.2.4 on 2023-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorapi', '0003_elevator_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='num_floors',
            new_name='max_floors',
        ),
        migrations.AddField(
            model_name='building',
            name='min_floor',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
