# Generated by Django 4.2.4 on 2023-08-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorapi', '0004_rename_num_floors_building_max_floors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='max_floors',
            new_name='max_floor',
        ),
    ]
